services:
  mediforum:
    build: .
    image: mediforum:vulnerable
    container_name: mediforum
    ports:
      - "3003:3003"
    restart: unless-stopped
    networks:
      - 300b-vuln
networks:
  300b-vuln:
    external: true
