# DVWA — PHP. dvwa.300b.lab → dvwa:80
<VirtualHost *:80>
    ServerName dvwa.300b.lab
    ServerAlias dvwa

    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass        / http://dvwa:80/
    ProxyPassReverse / http://dvwa:80/

    RequestHeader set X-Forwarded-Proto "http"

    ErrorLog ${APACHE_LOG_DIR}/dvwa-error.log
    CustomLog ${APACHE_LOG_DIR}/dvwa-access.log combined
</VirtualHost>
