# NeoBank — Flask. neobank.300b.lab → neobank:3001
<VirtualHost *:80>
    ServerName neobank.300b.lab
    ServerAlias neobank bank.300b.lab

    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass        / http://neobank:3001/
    ProxyPassReverse / http://neobank:3001/

    RequestHeader set X-Forwarded-Proto "http"

    ErrorLog ${APACHE_LOG_DIR}/neobank-error.log
    CustomLog ${APACHE_LOG_DIR}/neobank-access.log combined
</VirtualHost>
